version: "3.9"
services:
  webapp:
    image: ubuntu:latest
    build:
      context: .
    ports:
      - 8282:80
    volumes:
      - .:/var/www/html:Z
      - vendor:/var/www/html/vendor 
      - storage:/var/www/html/storage

volumes:
  vendor:
  storage:

